language: node_js
version: 1.0
node_js:
  - node
branches:
  only:
    - master
    - "/^\\d{1}\\.\\d{1,2}.\\d{1,2}$/"
notifications:
  email:
    recipients:
      - me@hsuna.com
    on_success: never
    on_failure: always
before_deploy: npm run build
deploy:
  edge: true
  provider: npm
  email: me@hsuna.com
  api_key:
    secure: YGSVRAjzhRW3+4o6leVQlwVfYHaEF5gg5IaDgRa8ulx0bIdB2v0I3Z6VNYwnZfcn/l6InK3tze0xhRYQhYQVtNNuzpreSkwhuaLGhkVS64oEwExM/QKb2Li6/PI25CYYE6p0zOS8ioQSNCPAPveyxe48JEyExRA5q+IYdjuQ4VUacDvw5CYaGw8UeWpbtqL8Kx9An97+q1QxqVXgThPL+OYqOrF8CLzqr9P4YFFKxHTAedZBGN5HgV6SwBvCajF0/sdL2THolzqo0/9BhuvHonUj5CxRNcxGSg12V2w5sUIj0kfcnJaOA5G5uss1Za0yQA4X7Bj9Vqp2UNX69+Q9gcbvFs00sspo9ojzt7zmvwCxhkU2pagBEZfncRaXaFyoZUhxwq+z34YdjfuPEUT1iDkVgD+H+NPXKn7bP8ziypphKQWUA4ghiCkBWpyScWp9nm3GuzE9F5ybHO14gS9WtgullyCKXDTbq4gNf2+8+8q+tSicixUh32KnET+w0VrgXOA1N9r+kltQ6GY93XmCEd0w4auNNDPMsoQfCFq+bDQdMKg4zGLf2blaQCEkve5GvZc6uCFsuij16Q9igyG7aATrMNcdX+3whlCvrS7J75rdVy42TzL7bXF9TivV2xy6cQzm9fY9T06TSS2WxQV473v341Y2oscoJc43zlm1+os=
  on:
    tags: true
    repo: hsuna/babel-plugin-styled-components-pxtorem
scripts:
  - npm test
  - npm install codecov -g
after_success:
  - codecov -f coverage/*.json
